version: '3'

services:
  traefik:  
    image: traefik:3.2.1
    command:
      - "--configfile=/traefik.yml"
    commandx:  
      - "--api=true"  
      - "--api.insecure=true"  
      - "--providers.docker=true"  
      - "--entrypoints.ep_web.address=:80"
      - "--entrypoints.ep_webtls.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=lrobot.qq@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/traefik_data/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "9001:8080"
    volumes:
      - ./traefik.yml:/traefik.yml
      - ./traefik_file_provider:/traefik_file_provider
      - /run/podman/podman.sock:/var/run/docker.sock:ro
  whoami:
    image: traefik/whoami
    # ports:
    #   - "8007:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoamilocalhost.rule=Host(`whoami.docker.localhost`)"
      - "traefik.http.routers.whoami80.rule=Host(`whoami.danfestar.cn`)"
      - "traefik.http.routers.whoami80.entrypoints=ep_web"
      - "traefik.http.routers.whoami443.rule=Host(`whoami.danfestar.cn`)"
      - "traefik.http.routers.whoami443.entrypoints=ep_webtls"
      - "traefik.http.routers.whoami443.tls=true"
      - "traefik.http.routers.whoami443.tls.certresolver=myresolver"
