api:
  basePath: /traefik
#  insecure: true
# log:
#   level: DEBUG
#   filePath: /__traefik_tmp_data/traefik.log
# accessLog:
#   filePath: /__traefik_tmp_data/access.log
providers:
  docker: {}
  file:
    directory: /traefik_file_provider/data
    watch: true
entryPoints:
  ep_web9k:
    address: ":9080"
  ep_web8k:
    address: ":8080"
  ep_webtls8k:
    address: ":8443"
  ep_web:
    address: ":80"
  ep_webtls:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      tlsChallenge: {}
      email: lrobot.qq@gmail.com
      storage: /__traefik_tmp_data/acme.json
      # httpChallenge:
      #   entryPoint: web
