api:
  insecure: true
# log:
#   level: DEBUG
#   filePath: /_traefik/traefik.log
# accessLog:
#   filePath: /_traefik/access.log
providers:
  docker: {}
  file:
    directory: /traefik_file_provider
    watch: true
entryPoints:
  web8000:
    address: ":8000"
  webtls8443:
    address: ":8443"
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      tlsChallenge: {}
      email: lrobot.qq@gmail.com
      storage: /_traefik/acme.json
      # httpChallenge:
      #   entryPoint: web
