# if network_mode host not work may be need install new podman-compose by: curl -o /usr/local/bin/podman-compose https://raw.githubusercontent.com/containers/podman-compose/main/podman_compose.py

services:
  coturn:
    network_mode: "host"
    image: coturn/coturn
    command: ["-c", "/etc/coturn/turnserver.conf"]
    volumes: # chmod 777 coturn.conf
      - "./coturn.conf:/etc/coturn/turnserver.conf"
  #turnrs:
    # https://github.com/mycrl/turn-rs?tab=readme-ov-file#docker
    #network_mode: "host"
    #image: ghcr.io/mycrl/turn-server
    #volumes:
    #  - "./turn_rs.yml:/etc/turn-server/config.toml"
    #restart: always
  kurento:
    network_mode: "host"
    image: kurento/kurento-media-server:7.0.0
    volumes:
      - "./kurento.conf.json:/etc/kurento/kurento.conf.json"
    restart: always
  mqtt:
    ports:
      - "1883:1883"
      - "8083:8083"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mqtt.rule=Host(`${KMEETING_DOMAIN_NAME}`) && PathPrefix(`/mqtt`)"
      - "traefik.http.routers.mqtt.entrypoints=ep_webtls"
      - "traefik.http.routers.mqtt.tls.certresolver=myresolver"
      - "traefik.http.services.mqtt.loadbalancer.server.port=8083"
    image: bytebeamio/rumqttd
    volumes:
      - "./rumqttd.toml:/etc/rumqttd.toml"
    entrypoint: ["rumqttd", "-c", "/etc/rumqttd.toml"]
    restart: always
